name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["py38", "py39", "py310", "py311", "py312"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version}}
      - name: install tox
        run: python -m pip install --upgrade tox virtualenv pip
      - name: run tox
        run: tox -e py
